export * as UnpackFunctionPass from './UnpackFunctionPass.js';
export * as ASTDescramblePass from './ASTDescramblePass.js';
export * as LiteralOutliningPass from './LiteralOutliningPass.js';
export * as UnhoistPass from './UnhoistPass.js';
export * as UnflattenControlFlowPass from './UnflattenControlFlowPass/mod.js'
export * as FixParametersPass from './FixParametersPass.js';
export * as UnshuffleArrayPass from './UnshuffleArrayPass.js'
export * as UnmaskVariablePass from './UnmaskVariablePass.js';
export * as StringPass from './StringPass/mod.js';
export * as GlobalObjectPass from './GlobalObjectPass.js';
export * as CalculatorInlinePass from './CalculatorInlinePass.js';
export * as DummyFunctionPass from './DummyFunctionPass.js';
export * as DeadCodeRemovalPass from './DeadCodeRemovalPass.js';
export * as OutlineDispatchPass from './OutlineDispatchPass.js';
export * as LiftEvalFunctionsPass from './LiftEvalFunctionsPass.js';
export * as UnflattenFunctionPass from './UnflattenFunctionPass.js';
export * as FunctionHashPass from './FunctionHashPass.js';
export * as LockRemovalPass from './LockRemovalPass.js';
export * as PolyfillRemovalPass from './PolyfillRemovalPass.js';